backend:
  name: git-gateway
  branch: main

site_url: https://fmresumes.online
logo_url: /logo.jpg
media_folder: "public/uploads"
public_folder: "/uploads"
publish_mode: simple

collections:
  - name: "updates"
    label: "Updates"
    folder: "content/posts/updates"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "guides"
    label: "Guides"
    folder: "content/posts/guides"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "PDF", name: "pdf", widget: "file", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
